### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by Coderx11** [Rolv-Apneseth/rofi-games#35] opened 2024-12-08 12:04 UTC
sorry for the inconvinience but i cant get it work right 

![image](https://github.com/user-attachments/assets/e3cc4242-120b-44ed-a4ce-b25253c0e52e)

i tried changing the box path and all but it still didnt work 

![image](https://github.com/user-attachments/assets/f0b459f9-14b4-4c0d-ab05-a866da49822f)

**Comment by Rolv-Apneseth** [comment] 2024-12-08 12:14
Could you specify a bit more? Do both entries not show up at all, or they don't launch etc.? And could you give me the output of `RUST_LOG=debug rofi -modi games -show games`.

Your top config (first image) looks correct so I'll need more info.

**Comment by Coderx11** [comment] 2024-12-09 14:12
sorry for the late response this is how it looks 
![image](https://github.com/user-attachments/assets/aff12de6-4a10-4001-9baa-1790c559388a)

**Comment by Rolv-Apneseth** [comment] 2024-12-09 14:22
If you don't mind, could you just post the text for everything going forward actually, it's easier to work with than an image. Setup looks clean though

**Comment by Coderx11** [comment] 2024-12-09 14:33
i thought space might be craeting a problem as when i open with terminal its not GOG Games but GOG\ Games so i renamed the folder 

![image](https://github.com/user-attachments/assets/5d4c0757-1fb1-4526-8644-d214451b72a5)

still the same and i hope i get it as i did in first one

**Comment by Coderx11** [comment] 2024-12-09 14:42
sorry for that i thought picture was more efficient because im kind of busy sorry for inconvenience :( 

and showing my setup wasent my intention :( but thanks for the praise ( no i feel embarrassed ( in negative way) for some reason )   

```

[[entries]]
title = "Celeste"
launch_command = " /home/harsh/GOG-Games/Celeste/Celeste.bin.x86_64"
# Looks for the image in the defined `box_art_dir`
path_box_art = "/home/harsh/GOG-Games/Celeste/Celeste.png"
path_game_dir = "/home/harsh/GOG-Games/Celeste/"

```

```
XD :: ~ » RUST_LOG=debug rofi -modi games -show games       
xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN" (mapped to "en_IN.ISO8859-1")
DEBUG lib_game_detector::linux::launchers::steam::steam_base: 177: Steam dir path exists: true
DEBUG lib_game_detector::linux::launchers::steam::steam_shortcuts: 202: Steam userdata dir path exists: true
DEBUG lib_game_detector::linux::launchers::heroic::heroic_gog: 68: Heroic GOG installed games json file exists: false
DEBUG lib_game_detector::linux::launchers::heroic::heroic_epic: 31: Heroic Launcher's legendary_library json file exists: false
DEBUG lib_game_detector::linux::launchers::heroic::heroic_amazon: 31: Heroic Launcher's nile_library json file exists: false
DEBUG lib_game_detector::linux::launchers::lutris: 204: Lutris - using flatpak: true
DEBUG lib_game_detector::linux::launchers::lutris: 206: Lutris - games directory exists at "/home/harsh/.var/app/net.lutris.Lutris/data/lutris/games": false
DEBUG lib_game_detector::linux::launchers::lutris: 210: Lutris - fallback games directory exists at "/home/harsh/.local/share/lutris/games": false
DEBUG lib_game_detector::linux::launchers::lutris: 214: Lutris - box art directory exists at "/home/harsh/.var/app/net.lutris.Lutris/data/lutris/coverart": false
DEBUG lib_game_detector::linux::launchers::lutris: 218: Lutris - fallback box art directory exists at "/home/harsh/.local/share/lutris/coverart": false
DEBUG lib_game_detector::linux::launchers::lutris: 222: Lutris - `game-paths.json` file exists at "/home/harsh/.var/app/net.lutris.Lutris/cache/lutris/game-paths.json": false
DEBUG lib_game_detector::linux::launchers::bottles: 167: Bottles - using flatpak: true
DEBUG lib_game_detector::linux::launchers::bottles: 168: Bottles - data directory exists: false
DEBUG lib_game_detector::linux::launchers::bottles: 172: Bottles - directory exists: false
DEBUG lib_game_detector::linux::launchers::bottles: 173: Bottles - library yaml file exists: false
DEBUG get_detected_games:get_steam_libraries{self=Steam { path_steam_dir: "/home/harsh/.local/share/Steam", is_using_flatpak: false }}: lib_game_detector::linux::launchers::steam::steam_base: 190: Steam libraryfolders.vdf path: "/home/harsh/.local/share/Steam/steamapps/libraryfolders.vdf"
 WARN get_detected_games: lib_game_detector::linux::launchers::steam::steam_shortcuts: 276: Steam Shortcuts - No valid shortcuts found
DEBUG rofi_games::config: 29: Config file found at "/home/harsh/.config/rofi-games/config.toml"
```

![image](https://github.com/user-attachments/assets/6a242adf-d1d4-49d0-9971-51a6d4a92cfd)

this is my file structure 

![image](https://github.com/user-attachments/assets/bf2c3d24-4ec5-47dd-a9c6-93f1975bbd1b)

**Comment by Rolv-Apneseth** [comment] 2024-12-09 14:43
Don't worry, and thanks for the info. I think I know where the issue is, probably broke the custom entries with the last update. I will fix today and hopefully have an update later

**Comment by Coderx11** [comment] 2024-12-09 14:45
thanks sir i thought i did something wrong thanks for support have a great day :)

**Comment by Rolv-Apneseth** [comment] 2024-12-09 17:37
Thanks for opening this issue. It's hopefully fixed now with `v1.10.7`, and that should be available on the AUR now (or re-install however you originally installed it). Let me know if that fixes it for you

**Comment by Coderx11** [comment] 2024-12-10 02:55
i made it sync with my color scheme and did some tweaks to the icons and  its working great now 

![image](https://github.com/user-attachments/assets/e7bab380-b5a0-4a2d-a4d2-8eb20c8a36a4)

**Closed** 2024-12-10 02:55 UTC

**Comment by Coderx11** [comment] 2024-12-10 04:09
@Rolv-Apneseth 
sir i think you should mention this in your wiki that you need to add \\ before spaces in launch_command but not in the file path 
Example ;
```
 [[entries]]
 title = "Stardew Valley"
 launch_command = "/home/harsh/GOG\\ Games/Stardew\\ Valley/start.sh"
  #Looks for the image in the defined box_art_dir
 path_box_art = "/home/harsh/GOG Games/Stardew Valley/support/icon.png"
 path_game_dir= "/home/harsh/GOG Games/Stardew Valley/"


```

**Comment by Rolv-Apneseth** [comment] 2024-12-10 13:33
> i made it sync with my color scheme and did some tweaks to the icons and its working great now

Great to hear

> sir i think you should mention this in your wiki that you need to add \\ before spaces in launch_command but not in the file path

Sure, I can make a note of it. If you were running in a shell, you would need one `\` for each space anyway, but I guess you need the double slash to escape it in `toml` (escaping the slash, so that when we parse the command it gets read correctly with the single slash).
